services:
  app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/HontoDare
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: astayoucode

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: HontoDare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: astayoucode
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: